# Generated by Django 4.1.7 on 2023-06-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TehnoMarket', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='TehnoMarket.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TehnoMarket.product')),
            ],
        ),
    ]
