# Generated by Django 4.1.7 on 2023-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TehnoMarket', '0004_product_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.IntegerField(),
        ),
    ]
